### PR TITLE
note about login/compute nodes, and quota

### PR DESCRIPTION
**Pull request by jdlaurence**
two relatively minor additions--a note about how login nodes and compute nodes are system specific, and a new faq about what to do when you're over quota (and I link to that from the data storage page)

### CODE REVIEW

**Comment by jdlaurence** [comment]
note that these are in response to #76 and #78

**Comment by pcarbo** [comment]
Looks good, JD. I'll only add for the quota remedies that another approach is to compress files or create tar archives.

**Review by pcarbo — CHANGES_REQUESTED** [review]
Looks good, JD. I'll only add for the quota remedies that another approach is to compress files or create tar archives.

**Review by ndtrung81 — CHANGES_REQUESTED** [review]
" and likewise Midway3 compute nodes can only be accessed from Midway3 login nodes." Other than this typo, the changes look good to me.

**Comment by pcarbo** [comment]
Well, compression is helpful for reducing storage used as well as the number of files, right?

**Comment by jdlaurence** [comment]
Very much true. Updated

**Review by pcarbo — APPROVED** [review]

**Pull request merged**
