### PR TITLE
Updates to the jupyter notebook page

### PR DESCRIPTION
**Pull request by ndtrung81**
This PR updates the jupyter notebook launches on Midway2 and Midway3 as of April 2023.

### CODE REVIEW

**Review by pcarbo — COMMENTED** [review]
Looks good. One comment: Trung, my understanding is that prior to April, `jupyter notebook --ip` did not work even with VPN, and one had to do ssh tunneling. So the question is about ssh tunnelling, not VPN vs. no VPN.

**Comment by ndtrung81** [comment]
@pcarbo you are correct, jupyter notebook didn't work even with VPN. And then in March ssh tunneling didn't work either, with and without VPN as far as my tests went on Midway2. In April, Midway2 via ssh works with and without VPN. Midway3 via ssh works only with VPN, as described in this PR.

**Comment by pcarbo** [comment]
@ndtrung81 Just so I'm clear, I can use `jupyter notebok --ip=...` *without SSH tunneling* on midway3 (if I use VPN)?

**Comment by ndtrung81** [comment]
@pcarbo as of this moment and in my test two days ago, yes, it works with `jupyter notebook --ip=128.135.x.y --port=[different from 8888]` without SSH tunneling on Midway3 if I use VPN.

**Comment by pcarbo** [comment]
Yes, I can confirm this works. Very nice.

We should still keep the SSH tunnelling instructions then for (external) people using midway3 that do not have access to VPN.

**Pull request merged**
