### PR TITLE
Updated the jupyter notebook steps based on the instructions offered …

### PR DESCRIPTION
**Pull request by ndtrung81**
…by Peter and Parm (thanks!)

We need these updates to refer users/questions from RT to.

### CODE REVIEW

**Comment by ndtrung81** [comment]
@pcarbo @pnsinha I tried to combine your instructions into the existing one. Requests to change are welcome and appreciated.

**Review by jdlaurence — APPROVED** [review]
These are great changes. Looks ready to me

**Comment by ndtrung81** [comment]
cool, let's see if @pcarbo and @pnsinha want to make further edits.

**Comment by pcarbo** [comment]
Well, at least I can follow these instructions. :)

**Comment by jdlaurence** [comment]
@pcarbo  can you formally 'approve' the changes (if you approve!)

**Review by pcarbo — APPROVED** [review]

**Pull request merged**
